// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-eUAkpyvRaWk3y2lwk71Qik-J3K6ITao',
    appId: '1:1007701548500:web:40fcdaae05ffb7cf3d8a41',
    messagingSenderId: '1007701548500',
    projectId: 'waterreminderapp',
    authDomain: 'waterreminderapp.firebaseapp.com',
    storageBucket: 'waterreminderapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjOPXhJOzzQX5iQ8tQTyVz9Fsr01ekcaA',
    appId: '1:1007701548500:android:93f5fcb3966a27ef3d8a41',
    messagingSenderId: '1007701548500',
    projectId: 'waterreminderapp',
    storageBucket: 'waterreminderapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRyZq5Y42ThVns74LVzT6dtdC5e0WeHeU',
    appId: '1:1007701548500:ios:4bf2454858316b963d8a41',
    messagingSenderId: '1007701548500',
    projectId: 'waterreminderapp',
    storageBucket: 'waterreminderapp.appspot.com',
    iosClientId: '1007701548500-di81bqf0c6qahut1n03ht0m72cnn27aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRyZq5Y42ThVns74LVzT6dtdC5e0WeHeU',
    appId: '1:1007701548500:ios:4bf2454858316b963d8a41',
    messagingSenderId: '1007701548500',
    projectId: 'waterreminderapp',
    storageBucket: 'waterreminderapp.appspot.com',
    iosClientId: '1007701548500-di81bqf0c6qahut1n03ht0m72cnn27aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterReminderApp',
  );
}
